- server.js
Documents for certain keys are not present. Hence the build is throwing error on trying to access the same. Fix that by checking whether a document is present before accessing it's properties
> fix: Access href only if document is present for the key

- scripts/at-rules.js
Image replace in at rules does not take the indent into consideration. This breaks the markdown rendering logic of numbered lists. Fix the same by considering the indent of an image tag
> fix: Fix image breaking the numbering in a numbered list

- scripts/at-rules.js
- scripts/custom-link.js
- scripts/md.js
- server.js
- webpack.config.js
Internal links are defined by content writers with the base url as /docs/...
This works for prod razorpay docs as the public path is /docs/. Update the urls to automatically take the public path in config as the base url
> feat: Rewrite internal links based on public path

- create-redirects.js
- server.js
Async redirect file creation keeps too many open descriptors and fails. Making it synchronous
> fix: Make redirect file creation synchronous

- server.js
Currently, the plugins only get the content and associated anchors for a page. This pr adds frontmatter to it.
> fix(Plugins): Send frontmatter to plugins

- server.js
Each plugin may decide to change either the raw body or the parsed markdown content. 
Citadel to send both to the plugins
> fix(plugins): Send document url to plugins

- scripts/cfs.js
Only lookup /index.md file for markdown files.
To support the new content structure introduced by the CMS, currently we are trying to access /index.md file for each file that is not present in the filesystem. Even though this is only required for content (markdown) files, this is currently being done for all kinds of files including assets.
> feat(cjs): try searching for /index.md only for markdown files

- server.js
- Currently while searching for any keyword in the docs, the results show `@include` statements rather than data of that file.
- This [file](https://github.com/razorpay/docs/blob/poc/docs-universe-ssg/src/routes/payment-links/reminders.md) includes a partial file.
- The content which is passed to the search plugin during the build for indexing, contains the raw markdown data of that file (i.e. containing `@include` statements) rather than the actual data of the imported file. Due to which the search results show incorrect data.
- I am just passing the final compiled markdown to the search plugin
> fix: passing complete mdx content to search plugin

- scripts/at-rules.js
Images can be put inside different tags such as "a" tag etc. These images need to be parsed and process by the at-rules processor
Img tag need not be present at the start of a file. Update regex to read img tag anywhere
> fix: extract images inside other tags

- scripts/at-rules.js
File tags can be put within other tags. However, the current regex expects the file tag to start at the beginning of a new file. Change the regex to allow to parse file tags anywhere in the content
- Update regex
> feat: match file tag anywhere in markdown

- build-helpers.js
- build-search.js
- index.js
- package-lock.json
- CMS content and direct changes that are done in `src/routes` trigger 2 separate deploy actions and due to which, search.json of one workflow is overridden by the other
- Due to this CMS pages changes don't show up in search results
- adds script for building seach.json file independently from the file build folder
> feat: add build search script

- generate-js.js
Problem
Home page search results redirect to cloudfront URL of the page
Solution
adds base path in config which would be used by search results in the website
> add base path in config

- index.js
- server.js
Problem: redirect files were being written every time a serve command from citadel was being run. All the files were being written regardless of changed files due to which serve was taking about 20 sec to complete.
Hence removed createRedirects step in case of serve (needed in case of build only).
> refactor: removed create config step in serve

- build-search.js
- scripts/at-rules.js
- server.js
- Adds util in `at-rules` script to validate missing required attributes and having value `undefined` in HTML and fail the build on validation fail
- This change is required to prevent the build to pass with buggy content
- More context on the issue that happened [here](https://github.com/razorpay/docs/pull/4407)
Example error message for required attributes missing 👇
Example error message for attribute with value `undefined` 👇
> add html attributes validation util

- build-helpers.js
- index.js
- server.js
- Currently, there's no check in the build system if paths defined in `tree` exist or not
- If a folder doesn't exist at the path given in `tree`, [an empty item is seen in the left sidebar](https://razorpay.com/docs/x/quickbooks/delete/) 👇  
- The expected behaviour is the build should fail with an error instead of successfully completing
- To fix the above issue, this PR refactors the build script to fail if the path defined in `tree` doesn't exist with an error 👇
> feat: fail build on file at path defined in tree doesn't exist

- build-helpers.js
- fs-helpers.js
- index.js
The current Citadel structures assumes the tree in a doc to be present either in the doc or any of it's closest parent till L0. But in case of our current Idocs we have all the tree defined only in main `index.md` file. Due to which Idocs was failing with the new version of citadel.
This PR contains the fix for above issue. The corresponding IDocs PR can be found [here](https://github.com/razorpay/idocs/pull/132)
> fix: added code to add default indexDoc when indexDoc's tree is not there

- build-helpers.js
Currently,  the title is being used as the heading for the page as well. This is not ideal as we may want different headings and titles. This PR adds support for the Heading field in frontmatter.
- Add normalizeFrontmatter function
- Take heading from frontmatter if present, else take the title and set it as heading
> feat: add support for heading in frontmatter

- scripts/html_block.js
- In a few places, table renders an extra `td` 👇🏻. Check it live [here](https://razorpay.com/docs/payments/payment-gateway/ecommerce-plugins/wix/faqs/#2-i-am-getting-the-following-error-during)
- This is happening because `<table>` tag isn't properly indented in the content. Check the indentation here https://raw.githubusercontent.com/razorpay/docs/master/production/content/routes/payments/payment-gateway/ecommerce-plugins/wix/faqs/index.md?token=GHSAT0AAAAAABUZBBCWBZ24A6AHTQS4EC2CYXBF3TQ
- I played around a bit and found the indentation to be the issue. As soon as I fix that, it seems to be rendering properly.
- Due to this, the ending `</table>` tag is received in the parsing function which renders it as an extra `td` in the row  
- Keeping a check in custom HTML parser, if td content …
> fix: trim space and check for empty html tag

- build-helpers.js
This PR removes the code that combines root doc frontmatter and current doc frontmatter. 
Combining the frontmatter had issues in overriding locale specific title and desc. 
[Slack Thread](https://razorpay.slack.com/archives/C03BD0J6DNC/p1681457705892469)
> fix(search): remove combining root frontmatter

- build-search.js
- package-lock.json
- package.json
- plugins.js
- scripts/at-rules.js
- scripts/md.js
1. Extend md utitlity to close unclosed tags.
**Reason** : In Citadel's markdown to html parser, some tags were left unclosed which generates incorrect html syntax. This generated html is used to build Algolia records.
Until now, we were not doing HAST parsing while building Algolia records, hence, this error went unnoticed. Now, we are parsing HAST for generating granular search records. Hence need this fix.
2. Trim indentation of md content before rendering to html
**Reason**: if content is not trimmed, then this results in incorrect interpretation of indentation resulting in errors like adding codeblocks whenver indentation > 3 etc. One more benefit of this is that record size is decreased by a great extent. No of heaving records decreased from 12 to 4.
> fix: close unclosed tags in html parser and trim indentation of md content lines
